server {
    listen 80;
    listen [::]:80;
    server_name tv.moling.fun;
    root /var/www/tv-moling-fun-acme;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
