events {}
http {
  server {
    listen 8080;
    location / { proxy_pass http://web:3000; }
    location /v1 { proxy_pass http://api:3001; }
    location /collab { proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_pass http://collab:3002; }
  }
}
