CREATE ROLE comic_migrator LOGIN;
CREATE ROLE comic_security_owner NOLOGIN NOINHERIT BYPASSRLS;
CREATE ROLE comic_operations NOLOGIN NOINHERIT NOBYPASSRLS;
CREATE ROLE comic_api LOGIN NOINHERIT NOBYPASSRLS;
CREATE ROLE comic_collab LOGIN NOINHERIT NOBYPASSRLS;
CREATE ROLE comic_dispatcher LOGIN NOINHERIT NOBYPASSRLS;
CREATE ROLE comic_generation_worker LOGIN NOINHERIT NOBYPASSRLS;
CREATE ROLE comic_media_worker LOGIN NOINHERIT NOBYPASSRLS;
